services:

  store-gateway:
    image: node:18-alpine
    env_file:
      - .env
    logging:
      driver: gcplogs
      options:
        gcp-project: "quid-labs"
    command: sh -c "cd dist/apps/store-gateway && node main"
    ports:
      - 3000:3000
    working_dir: /store-apis
    volumes:
      - ./:/store-apis
