services:

  store-gateway:
    image: node:18-alpine
    command: sh -c "cd dist/apps/store-gateway && node main"
    ports:
      - 3000:3000
    working_dir: /store-apis
    volumes:
      - ./:/store-apis
