services:

  store-gateway:
    image: node:18-alpine
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: quid-qa-log_group-store_store_gateway-eu-central-1
    command: sh -c "cd dist/apps/store-gateway && node main"
    ports:
      - 3000:3000
    working_dir: /store-apis
    volumes:
      - ./:/store-apis
