name: PR Checks

on:
  pull_request:
    branches:
      - dev
      - minor
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install npm dependencies
        run: yarn

      - name: Run Lint
        run: npx nx affected --target=lint --parallel=3 --base=remotes/origin/dev --head=remotes/origin/${{ steps.branch-name.outputs.current_branch }}

      - name: Run Unit Tests
        run: npx nx affected --target=test --parallel=3 --base=remotes/origin/dev --head=remotes/origin/${{ steps.branch-name.outputs.current_branch }}
